import { 
  Image, 
  FileText, 
  Calculator, 
  Type, 
  Code, 
  Palette, 
  Wrench,
  FileImage,
  Maximize,
  Crop,
  RotateCw,
  Languages,
  FileUp,
  FileDown,
  Files,
  Lock,
  PenTool,
  Hash,
  Calendar,
  Activity,
  DollarSign,
  Percent,
  RefreshCw,
  CaseSensitive,
  Binary,
  Trash2,
  SortAsc,
  Shield,
  Braces,
  Link,
  Pipette,
  CheckCircle,
  QrCode,
  Barcode,
  Clock,
  Dices
} from 'lucide-react';
import { CategoryInfo } from './types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'Image', title: 'Image Tools', icon: Image, color: 'text-blue-500' },
  { id: 'Document', title: 'Document Tools', icon: FileText, color: 'text-orange-500' },
  { id: 'Calculator', title: 'Calculators', icon: Calculator, color: 'text-emerald-500' },
  { id: 'Text', title: 'Text Tools', icon: Type, color: 'text-purple-500' },
  { id: 'Developer', title: 'Dev Tools', icon: Code, color: 'text-indigo-500' },
  { id: 'Color', title: 'Color Tools', icon: Palette, color: 'text-pink-500' },
  { id: 'Utility', title: 'Utilities', icon: Wrench, color: 'text-amber-500' },
];
